<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="User" failures="1" tests="3" name="Test" time="14.809" errors="0" timestamp="2024-08-14T14:53:07 BDT">
  <testcase classname="day46.OrangeHRMTest" name="testlogo" time="0.033"/>
  <testcase classname="day46.OrangeHRMTest" name="testAppUrl" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmahlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmahlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at day46.OrangeHRMTest.testAppUrl(OrangeHRMTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testAppUrl -->
  <testcase classname="day46.OrangeHRMTest" name="testTitle" time="0.0">
    <skipped/>
  </testcase> <!-- testTitle -->
</testsuite> <!-- Test -->
